// Six realistic Bay City pilot offers. Used to seed the local dev store,
// and mirrored in supabase/seed.sql for the real database.
// Edit or delete freely from /admin once live.

export const SEED_OFFERS = [
  {
    business_name: "Riverside Taqueria",
    neighborhood: "Water Street",
    category: "food",
    headline: "Tacos + drinks for two",
    value_desc: "Dinner for two ~$40 → $0 + $25 cash",
    the_ask: "30s vertical reel: the trompo, two tacos up close, one bite reaction. Tag the shop.",
    spots_total: 5,
    spots_remaining: 5,
    deadline: "2026-08-15",
    status: "open",
  },
  {
    business_name: "Third Shift Brewing",
    neighborhood: "Midland Street",
    category: "nightlife",
    headline: "Flight + pint night for two",
    value_desc: "Tab up to $35 → $0 + $20 cash",
    the_ask: "30–45s: pour shot at the taps, patio vibe, cheers clip. Copyright-safe audio only.",
    spots_total: 4,
    spots_remaining: 4,
    deadline: "2026-08-10",
    status: "open",
  },
  {
    business_name: "Harbor Light Coffee",
    neighborhood: "Downtown",
    category: "food",
    headline: "Breakfast + latte for two",
    value_desc: "Order up to $28 → $0 + $15 cash",
    the_ask: "30s: latte art pour, pastry case, window seat shot. Morning light preferred.",
    spots_total: 6,
    spots_remaining: 6,
    deadline: "2026-08-20",
    status: "open",
  },
  {
    business_name: "Saginaw Bay Boat Co.",
    neighborhood: "Marina",
    category: "activity",
    headline: "2-hour pontoon rental",
    value_desc: "Rental ~$180 → $0 + $50 cash",
    the_ask: "45–60s: leaving the dock, open-water cruise, sunset if you can time it. Life jackets visible.",
    spots_total: 2,
    spots_remaining: 2,
    deadline: "2026-08-08",
    status: "open",
  },
  {
    business_name: "The Wenonah Motor Inn",
    neighborhood: "Uptown",
    category: "stay",
    headline: "One weeknight stay",
    value_desc: "Room ~$95 → $0 + $40 cash",
    the_ask: "45s room tour: door-open reveal, bed, bathroom, the neon sign at night.",
    spots_total: 3,
    spots_remaining: 3,
    deadline: "2026-08-30",
    status: "open",
  },
  {
    business_name: "Brooklyn Boyz Pizza",
    neighborhood: "Columbus Ave",
    category: "food",
    headline: "Large pizza + garlic knots",
    value_desc: "Order ~$32 → $0 + $15 cash",
    the_ask: "30s: cheese pull is mandatory. Counter, oven, box-open shot.",
    spots_total: 5,
    spots_remaining: 5,
    deadline: "2026-08-25",
    status: "open",
  },
];
