// Six realistic Bay City pilot offers. Used to seed the local dev store,
// and mirrored in supabase/seed.sql for the real database.
// Edit or delete freely from /admin once live.
//
// retail_value: what the customer would normally pay (shown struck-through)
// cash_bonus: dollars on top, 0 = perk only
// brief: the company-made shoot brief, auto-emailed on claim
// photo_url: optional real photo; falls back to /offer-art/{category}.png

export const SEED_OFFERS = [
  {
    business_name: "Riverside Taqueria",
    neighborhood: "Water Street",
    address: "912 Water St, Bay City, MI",
    lat: 43.5962, lng: -83.8873,
    category: "food",
    headline: "Tacos + drinks for two",
    retail_value: "$40",
    cash_bonus: 25,
    the_ask: "30s vertical reel: the trompo, two tacos up close, one bite reaction.",
    brief:
      "Film vertical (9:16), 30 seconds. Must-have shots: (1) the al pastor trompo spinning behind the counter, (2) close-up of two tacos on the blue table, (3) one honest bite + reaction. Tag @riversidetaqueria if you post. Natural sound or platform-licensed audio only. Best light is the window tables before 7pm.",
    spots_total: 5,
    spots_remaining: 5,
    deadline: "2026-08-15",
    status: "open",
    photo_url: "",
  },
  {
    business_name: "Third Shift Brewing",
    neighborhood: "Midland Street",
    address: "509 Midland St, Bay City, MI",
    lat: 43.6009, lng: -83.9021,
    category: "nightlife",
    headline: "Flight + pint night for two",
    retail_value: "$35",
    cash_bonus: 20,
    the_ask: "30–45s: pour shot at the taps, patio vibe, cheers clip.",
    brief:
      "Film vertical, 30–45 seconds. Must-have shots: (1) a pour at the taps — ask the bartender, they know, (2) the flight paddle on the barrel tables, (3) patio string lights + a cheers clip. No copyrighted music. Weeknights after 8 have the best atmosphere without the crush.",
    spots_total: 4,
    spots_remaining: 4,
    deadline: "2026-08-10",
    status: "open",
    photo_url: "",
  },
  {
    business_name: "Harbor Light Coffee",
    neighborhood: "Downtown",
    address: "117 Center Ave, Bay City, MI",
    lat: 43.5944, lng: -83.8891,
    category: "food",
    headline: "Breakfast + latte for two",
    retail_value: "$28",
    cash_bonus: 15,
    the_ask: "30s: latte art pour, pastry case, window seat shot.",
    brief:
      "Film vertical, 30 seconds. Must-have shots: (1) the latte art pour at the bar — baristas will slow down if you ask, (2) a slow pan of the pastry case, (3) your order at the big window seat. Morning light (before 10am) is the whole point of this shop. Tag @harborlightcoffee if posting.",
    spots_total: 6,
    spots_remaining: 6,
    deadline: "2026-08-20",
    status: "open",
    photo_url: "",
  },
  {
    business_name: "Saginaw Bay Boat Co.",
    neighborhood: "Marina",
    address: "1 Marina Dr, Bay City, MI",
    lat: 43.6018, lng: -83.8829,
    category: "activity",
    headline: "2-hour pontoon rental",
    retail_value: "$180",
    cash_bonus: 50,
    the_ask: "45–60s: leaving the dock, open-water cruise, sunset if you can.",
    brief:
      "Film vertical, 45–60 seconds. Must-have shots: (1) pulling away from the dock, (2) open-water cruising with the skyline behind you, (3) golden hour on the bay if you can time it (6–8pm slots). Life jackets visible in every shot — it's their license requirement. Book the slot by replying to this email.",
    spots_total: 2,
    spots_remaining: 2,
    deadline: "2026-08-08",
    status: "open",
    photo_url: "",
  },
  {
    business_name: "The Wenonah Motor Inn",
    neighborhood: "Uptown",
    address: "3820 N Euclid Ave, Bay City, MI",
    lat: 43.5883, lng: -83.8867,
    category: "stay",
    headline: "One weeknight stay",
    retail_value: "$95",
    cash_bonus: 40,
    the_ask: "45s room tour: door-open reveal, bed, bathroom, neon sign at night.",
    brief:
      "Film vertical, 45 seconds. Must-have shots: (1) key-in-door opening reveal, (2) slow pan across the bed and the restored 60s furniture, (3) the bathroom, (4) the neon sign after dark — it's the money shot. Check-in Sun–Thu only. Reply to this email with your date before booking.",
    spots_total: 3,
    spots_remaining: 3,
    deadline: "2026-08-30",
    status: "open",
    photo_url: "",
  },
  {
    business_name: "Brooklyn Boyz Pizza",
    neighborhood: "Columbus Ave",
    address: "1214 Columbus Ave, Bay City, MI",
    lat: 43.5851, lng: -83.8785,
    category: "food",
    headline: "Large pizza + garlic knots",
    retail_value: "$32",
    cash_bonus: 15,
    the_ask: "30s: cheese pull (mandatory), counter, oven, box-open shot.",
    brief:
      "Film vertical, 30 seconds. Must-have shots: (1) the box-open reveal, (2) THE CHEESE PULL — non-negotiable, do it while it's hot, (3) the deck oven behind the counter if they're not slammed. Lunch (11–1) is calmest for counter shots. Tag @brooklynboyzbc if posting.",
    spots_total: 5,
    spots_remaining: 5,
    deadline: "2026-08-25",
    status: "open",
    photo_url: "",
  },
];
